### 규칙에 맞는 순번 생성 >> 시퀀스

# DEPT 테이블 사용하여 DEPT_SEQUENCE

CREATE TABLE DEPT_SEQUENCE
AS SELECT * FROM DEPT WHERE 1<>1;

SELECT*FROM DEPT_SEQUENCE;

# 시퀀스 생성 
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    CACHE 2;

# 시퀀스 쿼리로 확인
SELECT * FROM USER_SEQUENCES;

# 시퀀스 이용 데이터 삽입
INSERT INTO DEPT_SEQUENCE (DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');  (10식 증가 INCREMENT BY 10)

SELECT *FROM DEPT_SEQUENCE;

# 가장 마지막으로 생성된 시퀀스번호 확인 
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

# 시퀀스 옵션수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;
    

# 수정
SELECT *FROM USER_SEQUENCES;

# 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;
