# 사용자 만들기
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

# 권한 부여
#GRANT CREATE SESSION TO ORCLSTUDY;
# 계정에 권한 부여
GRANT CREATE SYNONYM TO hr;
GRANT CREATE PUBLIC SYNONYM TO hr;

# 모든 사용자 조회
SELECT *FROM ALL_USERS;
SELECT *FROM DBA_USERS;
SELECT *FROM DBA_OBJECTS;

# PL/SQL 기초
#SET SERVEROUTPUT ON;
#BEGIN
#    DBMS_OUTPUT.PUT_LINE('HELLO,PL/SQL')
#END;    

select * from EMP ;
