/*
SUM(컬럼명) OVER( PARTITION BY [컬럼] ORDER BY [컬럼] [ASC/DESC]
  ROWS / RANGE
  BETWEEN UNBOUNDED PRECEDING / PRECEDING / CURRENT ROW
      AND UNBOUNDED FOLLOWING / CURRENT ROW)

ROW : 부분집합인 윈도우 크기를 물리적인 단위로 행 집합을 지정
RANGE : 논리적인 주소에 의해 행 집합을 지정
UNBOUNDED PRECEDING : 윈도우의 시작 위치가 첫번째 ROW
UNBOUNDED FOLLOWING : 윈도우의 마지막 위치가 마지막 ROW
CURRENT ROW : 윈도우의 시작 위치가 현재 ROW
*/         
          
SELECT SAL,
  SUM(SAL) OVER(PARTITION BY JOB ORDER BY EMPNO
    ROWS BETWEEN UNBOUNDED PRECEDING  AND CURRENT ROW) 누적합계,        -- 첫째ROW부터 현재ROW까지
  SUM(SAL) OVER(PARTITION BY JOB ORDER BY EMPNO
    ROWS BETWEEN CURRENT ROW  AND UNBOUNDED FOLLOWING) 누적합계_반대    -- 현재ROW부터 마지막ROW까지
FROM EMP
WHERE JOB = 'MANAGER'

