# INNER JOIN   교집합
SELECT * 
FROM A INNER JOIN B ON A.CODE = B.CODE

# LEFT OUTER JOIN
SELECT *
FROM A LEFT OUTER JOIN B ON A.CODE = B.CODE

# RIGHT OUTER JOIN
SELECT *
FROM A RIGHT OUTER JOIN B ON A.CODE = B.CODE

# FULL OUTER JOIN   전체조회
SELECT *
FROM A FULL OUTER JOIN B ON A.CODE = B.CODE

# CROSS JOIN    a*b
SELECT *
FROM A CROSS JOIN B 
또는
SELECT *
FROM A, B 

# 테이블 A의 값 - 교집합
SELECT *
FROM A LEFT OUTER JOIN B ON A.CODE = B.CODE
WHERE B.CODE IS NULL

# 전체 - 교집합
SELECT *
FROM A FULL OUTER JOIN B ON A.CODE = B.CODE
WHERE A.CODE IS NULL OR B.CODE IS NULL

